//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a parameter.
func (in *Bucket) DeepCopyInto(out *Bucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new deep copy of the Bucket.
func (in *Bucket) DeepCopy() *Bucket {
	if in == nil {
		return nil
	}
	out := new(Bucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of an object.
func (in *Bucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a parameter.
func (in *BucketList) DeepCopyInto(out *BucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Bucket, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy creates a new deep copy of the BucketList.
func (in *BucketList) DeepCopy() *BucketList {
	if in == nil {
		return nil
	}
	out := new(BucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of an object.
func (in *BucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies RcloneS3Spec into the target.
func (in *BucketSpec) DeepCopyInto(out *BucketSpec) {
	*out = *in
	if in.PodLabels != nil {
		out.PodLabels = make(map[string]string, len(in.PodLabels))
		for key, val := range in.PodLabels {
			out.PodLabels[key] = val
		}
	}
	if in.PodAnnotations != nil {
		out.PodAnnotations = make(map[string]string, len(in.PodAnnotations))
		for key, val := range in.PodAnnotations {
			out.PodAnnotations[key] = val
		}
	}
	if in.PodAffinity != nil {
		out.PodAffinity = new(corev1.PodAffinity)
		in.PodAffinity.DeepCopyInto(out.PodAffinity)
	}
	if in.NodeAffinity != nil {
		out.NodeAffinity = new(corev1.NodeAffinity)
		in.NodeAffinity.DeepCopyInto(out.NodeAffinity)
	}
	if in.Replicas != nil {
		out.Replicas = new(int32)
		*out.Replicas = *in.Replicas
	}
	if in.ExtraArgs != nil {
		out.ExtraArgs = make([]string, len(in.ExtraArgs))
		copy(out.ExtraArgs, in.ExtraArgs)
	}
	deepCopyResources(in.Resources, &out.Resources)
}

// DeepCopyInto copies RcloneS3Status into the target.
func (in *BucketStatus) DeepCopyInto(out *BucketStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// deepCopyResources safely copies ResourceRequirements.
func deepCopyResources(in corev1.ResourceRequirements, out *corev1.ResourceRequirements) {
	in.DeepCopyInto(out)
}
